- id: doi:10.1364/BOE.563592
  image: /images/publications/Sajjad_BOE_2025.jpg
  tags:
    - algorithm

- id: doi:10.1364/PRJ.547778
  image: /images/publications/Chen_PhotonicResearch_2025.jpg
  tags:
    - algorithm

- id: doi:10.21105/joss.07275
  tags:
    - software

- id: doi:10.1101/2025.01.03.631147
  images: /images/Liu_bioRxiv_2025.jpg
  tags:
    - theory

- id: doi:10.1364/OE.531588
  images: /images/publications/Li_OE_2024.jpg
  tags:
    - algorithm

- id: doi:10.1038/s41467-024-49291-0
  images: /images/publications/Dibaji_NatCommu_2024.jpg
  tags:
    - instrumentation

- id: doi:10.1038/s41592-024-02282-x
  images: /images/publications/Liu_NatMethod_2024.jpg
  tags:
    - software

- id: doi:10.1126/science.ade2676
  images: /images/publications/Deguchi_Science_2023.jpg
  tags:
    - application

- id: doi:10.1364/BOE.401836
  images: /images/publications/Li_BOE_2020.jpg
  tags:
    - theory

- id: doi:10.1038/s42003-020-0908-2
  images: /images/publications/Liu_CommuBio_2020.jpg
  tags:
    - algorithm

- id: doi:10.1038/s41592-020-0816-x
  images: /images/publications/Xu_NatMethod_2020.jpg
  tags:
    - algorithm

- id: doi:10.1038/s41592-018-0153-5
  images: /images/publications/Zhang_NatMethod_2018.jpg
  tags:
    - algorithm

- id: doi:10.1038/s41592-018-0053-8
  images: /images/publications/Mlodzianoski_NatMethod_2018.jpg
  tags:
    - instrumentation

- id: doi:10.1038/nmeth.4379
  images: /images/publications/Liu_NatMethod_2017.jpg
  tags:
    - software

- id: doi:10.1146/annurev-biophys-102521-112912
  images: /images/publications/Liu_AnnualReview_2022.jpg
  tags:
    - review

- id: doi:10.1371/journal.pone.0064320
  images: /images/publications/Cutler_PlosOne_2013.jpg
  tags:
    - instrumentation

- id: doi:10.1364/BOE.7.002219
  images: /images/publications/Meddens_BOE_2016.jpg
  tags:
    - instrumentation

- id: doi:10.1364/OE.21.029462
  images: /images/publications/Liu_OE_2013.jpg
  tags:
    - algorithm

- id: doi:10.1371/journal.pone.0123941
  images: /images/publications/Valley_PlosOne_2015.jpg
  tags:
    - instrumentation

- id: doi:10.1088/2050-6120/3/1/014003
  images: /images/publications/Broeken_MethodApplFluor_2015.jpg
  tags:
    - algorithm

- id: doi:10.1146/annurev-bioeng-060418-052203
  images: /images/publications/Liu_AnnualReview_2020.jpg
  tags:
    - review

- id: doi:10.1002/cphc.201300758
  images: /images/publications/Liu_ChemPhysChem_2013.jpg
  tags:
    - theory

- id: doi:10.1038/s44172-024-00205-4
  images: /images/publications/Prince_CommuEng_2024.jpg
  tags:
    - instrumentation

- id: doi:10.1364/BOE.477501
  images: /images/publications/Schodt_BOE_2022.jpg
  tags:
    - algorithm
    - instrumentation

